[pytest]
pythonpath = .
testpaths = Users_Test
addopts = -v -s --cov=Users_API --cov=Users_Application --cov=Users_Domain --cov=Users_Infrastruture --cov-report=term-missing --cov-report=xml --cov-report=html